export const DIRECTION_SERVICE_OFFER_BY_A_PARTNER = 3

export const DIRECTION_INFO_BY_A_THIRD_PARTY = 5


export const POST_COURSE_FOLLOWUP_DIRECTION = {
  1: "FOLDER.POST_COURSE_FOLLOWUP_DIRECTION.YOUNG_TOWARDS_STRUCTURE",
  2: "FOLDER.POST_COURSE_FOLLOWUP_DIRECTION.STRUCTURE_TOWARDS_YOUNG",
  [DIRECTION_SERVICE_OFFER_BY_A_PARTNER]: "FOLDER.POST_COURSE_FOLLOWUP_DIRECTION.SERVICE_OFFER_BY_A_PARTNER" ,
  4: "FOLDER.POST_COURSE_FOLLOWUP_DIRECTION.INTERNAL",
  [DIRECTION_INFO_BY_A_THIRD_PARTY]: "FOLDER.POST_COURSE_FOLLOWUP_DIRECTION.INFO_BY_A_THIRD_PARTY"
}



export const postCourseFollowUpDirectionUIHelper = (intl) =>
  Object.keys(POST_COURSE_FOLLOWUP_DIRECTION).map((key) => ({
    value: parseInt(key),
    label: intl.formatMessage({ id: POST_COURSE_FOLLOWUP_DIRECTION[key] }),
  }))
