export const TRAINING_INDICATION = 1
export const OCCUPATIONAL_INTEGRATION_INDICATION = 2
export const OTHER_INDICATION = 3

export const TYPES_SITUATION = { 
  [TRAINING_INDICATION]: "ORIENTATION.TYPE_SITUATION.TRAINING_INDICATION",
  [OCCUPATIONAL_INTEGRATION_INDICATION]: "ORIENTATION.TYPE_SITUATION.OCCUPATIONAL_INTEGRATION_INDICATION",
  [OTHER_INDICATION]: "ORIENTATION.TYPE_SITUATION.OTHER_INDICATION" ,
}

export const orientationSituationTypeUIHelper = (intl) =>
  Object.keys(TYPES_SITUATION).map((key) => ({
    value: parseInt(key),
    label: intl.formatMessage({ id: TYPES_SITUATION[key] }),
  }))
