const uIHelper = (OBJECT) => (intl) =>
  Object.keys(OBJECT).map((value) => ({
    value: parseInt(value),
    label: intl.formatMessage({ id: OBJECT[value] }),
  }))

export const HAS_ONE_PARENT_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.MOTHER_DEATH_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.FATHER_DEATH_INDICATION",
  3: "FOLDER.FAMILTY_INFORMATION.SINGLE_MOTHER_INDICATION"
}

export const hasOneParentIndicationsUIHelper = uIHelper(HAS_ONE_PARENT_INDICATIONS)

export const DISJOINTED_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.DIVORCE_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.SEPARATION_INDICATION",
  3: "FOLDER.FAMILTY_INFORMATION.ABSENT_INDICATION"
}

export const disjointedIndicationsUIHelper = uIHelper(DISJOINTED_INDICATIONS)

export const ONE_PARENT_ABSENCE_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.MIGRATION_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.PRISON_INDICATION"
}

export const oneParentAbsenceIndicationsUIHelper = uIHelper(ONE_PARENT_ABSENCE_INDICATIONS)


export const WITHOUT_SUPPORT_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.DEATH_BOTH_PARENTS_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.HELPLESSNESS_PARENTS_INDICATION",
  3: "FOLDER.FAMILTY_INFORMATION.FINAL_GIVE_UP_INDICATION"
}

export const withoutSupportTypeIndicationsUIHelper = uIHelper(WITHOUT_SUPPORT_INDICATIONS)


export const REGENERATIVE_FORMULA_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.MOTHER_REMARRIAGE_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.FATHER_REMARRIAGE_INDICATION"
}

export const regenerativeFormulaTypeIndicationsUIHelper = uIHelper(REGENERATIVE_FORMULA_INDICATIONS)


export const EXTENDED_FAMILY_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.MOTHER_PARENTS_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.FATHER_PARENTS_INDICATION"
}

export const extendedFamilyTypeIndicationsUIHelper = uIHelper(EXTENDED_FAMILY_INDICATIONS)


export const FAMILY_RECEPTION_INDICATIONS = {
  1: "FOLDER.FAMILTY_INFORMATION.WARRANTY_INDICATION",
  2: "FOLDER.FAMILTY_INFORMATION.ADOPTION_INDICATION",
  3: "FOLDER.FAMILTY_INFORMATION.FAMILY_DEPOSIT_INDICATION"
}

export const familyReceptionTypeIndicationsUIHelper = uIHelper(FAMILY_RECEPTION_INDICATIONS)
