
export const SCHOOL_DROPOUT_TRAINING_LEVEL_CC = 1
export const SCHOOL_DROPOUT_TRAINING_LEVEL_CAP = 2
export const SCHOOL_DROPOUT_TRAINING_LEVEL_BTP = 3
export const SCHOOL_DROPOUT_TRAINING_LEVEL_BTS = 4


export const TRAINING_LEVEL = {
  [SCHOOL_DROPOUT_TRAINING_LEVEL_CC]: "SCHOOL_DROPOUT.TRAINING_LEVEL.CC",
  [SCHOOL_DROPOUT_TRAINING_LEVEL_CAP]: "SCHOOL_DROPOUT.TRAINING_LEVEL.CAP",
  [SCHOOL_DROPOUT_TRAINING_LEVEL_BTP]: "SCHOOL_DROPOUT.TRAINING_LEVEL.BTP" ,
  [SCHOOL_DROPOUT_TRAINING_LEVEL_BTS]: "SCHOOL_DROPOUT.TRAINING_LEVEL.BTS"
}


export const schoolDropoutTrainingLevelUIHelper = (intl) =>
  Object.keys(TRAINING_LEVEL).map((key) => ({
    value: parseInt(key),
    label: intl.formatMessage({ id: TRAINING_LEVEL[key] }),
  }))
