export const THE_RETURN_TO_THE_INITIAL_TEACHING = 1
export const ACCESS_TO_QUALIFYING_TRAINING = 2
export const ACCESS_TO_DIRECT_EMPLOYMENT = 3
export const ABUNDANT = 4
export const EXIT_COURSE = {
    [THE_RETURN_TO_THE_INITIAL_TEACHING]: "FOLDER.STATUS.THE_RETURN_TO_THE_INITIAL_TEACHING",
  [ACCESS_TO_QUALIFYING_TRAINING]: "FOLDER.STATUS.ACCESS_TO_QUALIFYING_TRAINING",
  [ACCESS_TO_DIRECT_EMPLOYMENT]: "FOLDER.STATUS.ACCESS_TO_DIRECT_EMPLOYMENT͘",
  [ABUNDANT]: "FOLDER.STATUS.ABUNDANT"
}

export const exitCourseTypeUIHelper = (intl) =>
  Object.keys(EXIT_COURSE).map((key) => ({
    value: parseInt(key),
    label: intl.formatMessage({ id: EXIT_COURSE[key] }),
  }))
